function com_hirshi001_gwtrestapi_GWTRestAPI_JUnit(){var N='bootstrap',O='begin',P='gwt.codesvr.com.hirshi001.gwtrestapi.GWTRestAPI.JUnit=',Q='gwt.codesvr=',R='com.hirshi001.gwtrestapi.GWTRestAPI.JUnit',S='startup',T='DUMMY',U=0,V=1,W='iframe',X='position:absolute; width:0; height:0; border:none; left: -1000px;',Y=' top: -1000px;',Z='Chrome',$='CSS1Compat',_='<!doctype html>',ab='',bb='<html><head><\/head><body><\/body><\/html>',cb='undefined',db='readystatechange',eb=10,fb='script',gb='moduleStartup',hb='moduleRequested',ib='com_hirshi001_gwtrestapi_GWTRestAPI_JUnit',jb='Failed to load ',kb='head',lb='javascript',mb='meta',nb='name',ob='com.hirshi001.gwtrestapi.GWTRestAPI.JUnit::',pb='::',qb='gwt:property',rb='content',sb='=',tb='gwt:onPropertyErrorFn',ub='Bad handler "',vb='" for "gwt:onPropertyErrorFn"',wb='gwt:onLoadErrorFn',xb='" for "gwt:onLoadErrorFn"',yb='#',zb='?',Ab='/',Bb='img',Cb='clear.cache.gif',Db='baseUrl',Eb='com.hirshi001.gwtrestapi.GWTRestAPI.JUnit.nocache.js',Fb='base',Gb='//',Hb='selectingPermutation',Ib='com.hirshi001.gwtrestapi.GWTRestAPI.JUnit.devmode.js',Jb='05F1B51FAF00AD289264A6DD1FEBFA09',Kb=':',Lb='.cache.js',Mb='loadExternalRefs',Nb='end',Ob='http:',Pb='file:',Qb='_gwt_dummy_',Rb='__gwtDevModeHook:com.hirshi001.gwtrestapi.GWTRestAPI.JUnit',Sb='Ignoring non-whitelisted Dev Mode URL: ',Tb=':moduleBase';var n=window;var o=document;q(N,O);function p(){var a=n.location.search;return a.indexOf(P)!=-1||a.indexOf(Q)!=-1}
function q(a,b){if(n.__gwtStatsEvent){n.__gwtStatsEvent({moduleName:R,sessionId:n.__gwtStatsSessionId,subSystem:S,evtGroup:a,millis:(new Date).getTime(),type:b})}}
com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__sendStats=q;com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__moduleName=R;com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__errFn=null;com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__moduleBase=T;com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__softPermutationId=U;com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__computePropValue=null;com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__getPropMap=null;com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__installRunAsyncCode=function(){};com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__gwtStartLoadingFragment=function(){return null};com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__gwt_isKnownPropertyValue=function(){return false};com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__gwt_getMetaProperty=function(){return null};var r=null;var s=n.__gwt_activeModules=n.__gwt_activeModules||{};s[R]={moduleName:R};com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__moduleStartupDone=function(e){var f=s[R].bindings;s[R].bindings=function(){var a=f?f():{};var b=e[com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__softPermutationId];for(var c=U;c<b.length;c++){var d=b[c];a[d[U]]=d[V]}return a}};var t;function u(){v();return t}
function v(){if(t){return}var a=o.createElement(W);a.id=R;a.style.cssText=X+Y;a.tabIndex=-1;o.body.appendChild(a);t=a.contentWindow.document;if(navigator.userAgent.indexOf(Z)==-1){t.open();var b=document.compatMode==$?_:ab;t.write(b+bb);t.close()}}
function w(i){function j(a){function b(){if(typeof o.readyState==cb){return typeof o.body!=cb&&o.body!=null}return /loaded|complete/.test(o.readyState)}
var c=b();if(c){a();return}function d(){if(!c){if(!b()){return}c=true;a();if(o.removeEventListener){o.removeEventListener(db,d,false)}if(e){clearInterval(e)}}}
if(o.addEventListener){o.addEventListener(db,d,false)}var e=setInterval(function(){d()},eb)}
function k(c){function d(a,b){a.removeChild(b)}
var e=u();var f=e.body;var g;if(navigator.userAgent.indexOf(Z)>-1){g=e.createElement(fb);g.text=c.join(ab);f.appendChild(g);d(f,g)}else{for(var h=U;h<c.length;h++){g=e.createElement(fb);g.text=c[h];f.appendChild(g);d(f,g)}}}
com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.onScriptDownloaded=function(a){j(function(){k(a)})};q(gb,hb);var l=o.createElement(fb);l.src=i;if(com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__errFn){l.onerror=function(){com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__errFn(ib,new Error(jb+code))}}o.getElementsByTagName(kb)[U].appendChild(l)}
com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__startLoadingFragment=function(a){return C(a)};com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__installRunAsyncCode=function(a){var b=u();var c=b.body;var d=b.createElement(fb);d.language=lb;d.text=a;c.appendChild(d);c.removeChild(d)};function A(){var c={};var d;var e;var f=o.getElementsByTagName(mb);for(var g=U,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(nb),k;if(j){j=j.replace(ob,ab);if(j.indexOf(pb)>=U){continue}if(j==qb){k=i.getAttribute(rb);if(k){var l,m=k.indexOf(sb);if(m>=U){j=k.substring(U,m);l=k.substring(m+V)}else{j=k;l=ab}c[j]=l}}else if(j==tb){k=i.getAttribute(rb);if(k){try{d=eval(k)}catch(a){alert(ub+k+vb)}}}else if(j==wb){k=i.getAttribute(rb);if(k){try{e=eval(k)}catch(a){alert(ub+k+xb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};r=d;com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(yb);if(b==-1){b=a.length}var c=a.indexOf(zb);if(c==-1){c=a.length}var d=a.lastIndexOf(Ab,Math.min(c,b));return d>=U?a.substring(U,d+V):ab}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=o.createElement(Bb);b.src=a+Cb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Db);if(a!=null){return a}return ab}
function h(){var a=o.getElementsByTagName(fb);for(var b=U;b<a.length;++b){if(a[b].src.indexOf(Eb)!=-1){return e(a[b].src)}}return ab}
function i(){var a=o.getElementsByTagName(Fb);if(a.length>U){return a[a.length-V].href}return ab}
function j(){var a=o.location;return a.href==a.protocol+Gb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==ab){k=h()}if(k==ab){k=i()}if(k==ab&&j()){k=e(o.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__moduleBase+a}
function D(){var f=[];var g=U;var h=[];var i=[];function j(a){var b=i[a](),c=h[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(r){r(a,d,b)}throw null}
__gwt_isKnownPropertyValue=function(a,b){return b in h[a]};com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__getPropMap=function(){var a={};for(var b in h){if(h.hasOwnProperty(b)){a[b]=j(b)}}return a};com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__computePropValue=j;n.__gwt_activeModules[R].bindings=com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__getPropMap;q(N,Hb);if(p()){return C(Ib)}var k;try{k=Jb;var l=k.indexOf(Kb);if(l!=-1){g=parseInt(k.substring(l+V),eb);k=k.substring(U,l)}}catch(a){}com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__softPermutationId=g;return C(k+Lb)}
function F(){if(!n.__gwt_stylesLoaded){n.__gwt_stylesLoaded={}}q(Mb,O);q(Mb,Nb)}
A();com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__moduleBase=B();s[R].moduleBase=com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.__moduleBase;var G=D();if(n){var H=!!(n.location.protocol==Ob||n.location.protocol==Pb);n.__gwt_activeModules[R].canRedirect=H;function I(){var b=Qb;try{n.sessionStorage.setItem(b,b);n.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(H&&I()){var J=Rb;var K=n.sessionStorage[J];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(K)){if(K&&(window.console&&console.log)){console.log(Sb+K)}K=ab}if(K&&!n[J]){n[J]=true;n[J+Tb]=B();var L=o.createElement(fb);L.src=K;var M=o.getElementsByTagName(kb)[U];M.insertBefore(L,M.firstElementChild||M.children[U]);return false}}}F();q(N,Nb);w(G);return true}
com_hirshi001_gwtrestapi_GWTRestAPI_JUnit.succeeded=com_hirshi001_gwtrestapi_GWTRestAPI_JUnit();